version: "3.9"

services:
  pullback-trader:
    container_name: pullback-trader
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
      - ./data:/app/data
    restart: unless-stopped
