version: "3.9"

services:
  rsi-chaik-bot:
    container_name: rsi-chaik-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
      - ./data:/app/data
    restart: unless-stopped
